version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm install &&
             ng build --configuration production &&
             cp -r /app/dist/examen-carrion-diego/browser/* /var/www/html/ &&
             apachectl -D FOREGROUND"