version: "3.9"
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    volumes:
      - .:/app 
      - /app/node_modules 
      - /app/dist:/var/www/html 
    command: >
      sh -c "npm install &&
             ng build --watch --configuration development &&
             apachectl -D FOREGROUND"
